discovery:
  image: microservice/discovery
  hostname: discovery
  ports:
   - "8761:8761"
server:
  image: microservice/server
  ports:
   - "9000:9000"
  links:
   - discovery
client:
  image: microservice/client
  ports:
   - "9001:9001"
  links:
   - discovery
zuul:
  image: microservice/zuul
  ports:
   - "9002:9002"
  links:
   - discovery
   - client

