version: "3"
services:
  peer1:
    image: microservice/discovery
    ports:
    - "8761:8761"
    environment:
    - spring.profiles.active=peer1
  peer2:
    image: microservice/discovery
    hostname: peer2
    ports:
    - "8762:8762"
    environment:
    - spring.profiles.active=peer2
  server:
    image: microservice/server
    ports:
    - "9000:9000"
  client:
    image: microservice/client
    ports:
    - "9001:9001"
  zuul:
    image: microservice/zuul
    ports:
    - "9002:9002"