server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: client

