server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: client

